import os
from dotenv import load_dotenv

load_dotenv()


REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT"))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", None) or None
REDIS_DB = int(os.getenv("REDIS_DB", 0))

# -- SQL
CONNECTION_STRING = os.getenv("DB_CONNECTION")

# -- Keys

SECRET_KEY = os.getenv("SECRET_KEY")
SESSION_KEY = os.getenv("SESSION_KEY")
RESET_KEY = os.getenv("RESET_KEY")
UNLOCK_KEY = os.getenv("UNLOCK_KEY")

# -- Email

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = os.getenv("SMTP_PORT")
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")


# --- URLS

FRONTEND_EMAIL_VARIFICATION = os.getenv("FRONTEND_EMAIL_VARIFICATION")
FRONTEND_2FA_VARIFICATION = os.getenv("FRONTEND_2FA_VARIFICATION")
FRONTEND_RESET_VARIFITCATION = os.getenv("FRONTEND_RESET_VARIFITCATION")
FRONTEND_UNLOCK_VARIFITCATION = os.getenv("FRONTEND_UNLOCK_VARIFITCATION")
